### ISSUE TITLE
Neutral terms

### ISSUE THREAD

**Issue by RacheleSprugnoli** [WladimirSidorenko/SentiLex#2] opened 2019-11-18 10:56 UTC
Dear Wladimir,
is it ok that the output of word-embedding-based algorithms does not include any term with a neutral score? The label "neutral" appears only for the seed terms.
Thanks in advance,
best,
Rachele

**Comment by WladimirSidorenko** [comment] 2019-11-18 11:08
Hello Rachele,

Yes, that's intended behavior as I assume that people who generate lexicons will be primarily interested in polar (i.e., either positive or negative) terms.  But if you want neutral terms to be printed as well, you can comment or delete lines 199 and 200 in file `src/vec2dic/expansion.cpp` and recompile the project, then neutral terms should appear in the output as well.

Best regards
Wladimir

**Comment by WladimirSidorenko** [comment] 2019-11-19 10:25
@RacheleSprugnoli I'll close this ticket.  Feel free to re-open it, if there will be any further questions or unexpected results.

**Closed as completed by WladimirSidorenko** 2019-11-19 10:25 UTC
